const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  AlignmentType, HeadingLevel, BorderStyle, WidthType, ShadingType,
  LevelFormat, PageBreak
} = require('docx');
const fs = require('fs');

const border = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
const borders = { top: border, bottom: border, left: border, right: border };
const noBorders = {
  top: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  bottom: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  left: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  right: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
};

const COLOR = {
  blue: "1A5DAD",
  lightBlue: "DBEAFE",
  green: "166534",
  lightGreen: "DCFCE7",
  red: "991B1B",
  lightRed: "FEE2E2",
  amber: "92400E",
  lightAmber: "FEF3C7",
  teal: "0F6E56",
  lightTeal: "D1FAE5",
  gray: "374151",
  lightGray: "F3F4F6",
  darkGray: "1F2937",
  white: "FFFFFF",
};

function heading1(text, color = COLOR.blue) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    children: [new TextRun({ text, color, font: "Arial", size: 32, bold: true })],
    spacing: { before: 480, after: 200 },
  });
}

function heading2(text, color = COLOR.darkGray) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    children: [new TextRun({ text, color, font: "Arial", size: 26, bold: true })],
    spacing: { before: 360, after: 160 },
  });
}

function heading3(text, color = COLOR.gray) {
  return new Paragraph({
    children: [new TextRun({ text, color, font: "Arial", size: 24, bold: true })],
    spacing: { before: 280, after: 120 },
  });
}

function para(text, options = {}) {
  return new Paragraph({
    children: [new TextRun({ text, font: "Arial", size: 22, ...options })],
    spacing: { after: 100 },
  });
}

function divider(color = "DDDDDD") {
  return new Paragraph({
    border: { bottom: { style: BorderStyle.SINGLE, size: 1, color } },
    spacing: { after: 160 },
    children: [],
  });
}

function statusBadge(status, bgColor, textColor) {
  return new Table({
    width: { size: 1800, type: WidthType.DXA },
    columnWidths: [1800],
    rows: [new TableRow({
      children: [new TableCell({
        borders: noBorders,
        shading: { fill: bgColor, type: ShadingType.CLEAR },
        margins: { top: 60, bottom: 60, left: 120, right: 120 },
        width: { size: 1800, type: WidthType.DXA },
        children: [new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: status, font: "Arial", size: 18, bold: true, color: textColor })],
        })],
      })],
    })],
    margins: { bottom: 80 },
  });
}

function emailBox(subject, body) {
  const rows = [
    new TableRow({
      children: [
        new TableCell({
          borders: noBorders,
          shading: { fill: "F8FAFF", type: ShadingType.CLEAR },
          width: { size: 1440, type: WidthType.DXA },
          margins: { top: 80, bottom: 80, left: 160, right: 160 },
          children: [new Paragraph({ children: [new TextRun({ text: "Subject:", font: "Arial", size: 20, bold: true, color: COLOR.blue })] })],
        }),
        new TableCell({
          borders: noBorders,
          shading: { fill: "F8FAFF", type: ShadingType.CLEAR },
          width: { size: 7920, type: WidthType.DXA },
          margins: { top: 80, bottom: 80, left: 160, right: 160 },
          children: [new Paragraph({ children: [new TextRun({ text: subject, font: "Arial", size: 20, bold: true, color: COLOR.darkGray })] })],
        }),
      ],
    }),
    new TableRow({
      children: [
        new TableCell({
          columnSpan: 2,
          borders: { top: { style: BorderStyle.SINGLE, size: 1, color: "DDDDDD" }, bottom: border, left: border, right: border },
          shading: { fill: COLOR.white, type: ShadingType.CLEAR },
          width: { size: 9360, type: WidthType.DXA },
          margins: { top: 160, bottom: 160, left: 200, right: 200 },
          children: body.map(line =>
            new Paragraph({
              children: [new TextRun({ text: line, font: "Arial", size: 20, color: "#333333" })],
              spacing: { after: line === "" ? 80 : 60 },
            })
          ),
        }),
      ],
    }),
  ];

  return new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [1440, 7920],
    borders: {
      top: border, bottom: border, left: border, right: border,
      insideH: { style: BorderStyle.NONE }, insideV: { style: BorderStyle.NONE },
    },
    rows,
  });
}

function pageBreak() {
  return new Paragraph({ children: [new PageBreak()] });
}

function space(n = 1) {
  return [...Array(n)].map(() => new Paragraph({ children: [new TextRun("")], spacing: { after: 80 } }));
}

// ───────────────────────── TEMPLATE DATA ─────────────────────────

const templates = [
  {
    stage: "1. Application Received",
    stageColor: COLOR.blue,
    statuses: [
      {
        status: "Pending",
        badgeBg: "DBEAFE", badgeText: COLOR.blue,
        subject: "We've received your application – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for applying for the [Job Title] position at [Company Name]. We're pleased to confirm that your application has been successfully received.",
          "",
          "Our hiring team will carefully review your submission. We aim to respond within [X business days]. In the meantime, please feel free to explore more about us at [Company Website].",
          "",
          "We appreciate your interest and will keep you updated on the next steps.",
          "",
          "Warm regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Shortlisted",
        badgeBg: "DCFCE7", badgeText: COLOR.green,
        subject: "Great News! You've been shortlisted – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We are pleased to inform you that after reviewing your application for the [Job Title] role, you have been shortlisted for the next stage of our recruitment process.",
          "",
          "Our team was impressed with your profile and we look forward to learning more about you. You will hear from us shortly regarding the next steps.",
          "",
          "Thank you for your patience and continued interest in [Company Name].",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Rejected",
        badgeBg: "FEE2E2", badgeText: COLOR.red,
        subject: "Your application for [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for taking the time to apply for the [Job Title] position at [Company Name].",
          "",
          "After carefully reviewing your application, we regret to inform you that we will not be moving forward with your profile at this time. This decision was based on the specific requirements of the role and the volume of applications received.",
          "",
          "We encourage you to apply for future openings that align with your experience. We wish you all the best in your job search.",
          "",
          "Warm regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "On Hold",
        badgeBg: "FEF3C7", badgeText: COLOR.amber,
        subject: "Update on your application – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for your interest in the [Job Title] role at [Company Name].",
          "",
          "We wanted to let you know that your application is currently on hold due to [internal restructuring / role re-evaluation / a high volume of applications]. We will resume the review process by [approximate date] and will reach out to you then.",
          "",
          "We appreciate your patience and understanding during this time.",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
    ],
  },
  {
    stage: "2. Resume Screening",
    stageColor: COLOR.blue,
    statuses: [
      {
        status: "Pending",
        badgeBg: "DBEAFE", badgeText: COLOR.blue,
        subject: "Your resume is under review – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for your application for the [Job Title] position. We are currently reviewing your resume and assessing your qualifications against our requirements.",
          "",
          "We will notify you of the outcome within [X business days]. Please hold tight — we'll be in touch soon.",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Shortlisted",
        badgeBg: "DCFCE7", badgeText: COLOR.green,
        subject: "Resume shortlisted – Next steps for [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We're delighted to let you know that your resume has been reviewed and you have been shortlisted to proceed in the selection process for the [Job Title] role.",
          "",
          "We will reach out shortly to schedule the next step. Please keep an eye on your inbox for further communication.",
          "",
          "Thank you for your interest in [Company Name]!",
          "",
          "Warm regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Rejected",
        badgeBg: "FEE2E2", badgeText: COLOR.red,
        subject: "Your application for [Job Title] – Update from [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for applying for the [Job Title] position at [Company Name].",
          "",
          "After reviewing your resume, we've determined that your profile does not meet the specific requirements for this role at this time. We genuinely appreciate the effort you've put into your application.",
          "",
          "We wish you great success in your career journey and encourage you to apply for future openings that are a strong fit.",
          "",
          "Kind regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "On Hold",
        badgeBg: "FEF3C7", badgeText: COLOR.amber,
        subject: "Resume review on hold – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We wanted to give you a brief update regarding your application for the [Job Title] role.",
          "",
          "The resume screening process is currently on hold as we finalise the role requirements internally. We expect to resume the process by [expected date] and will contact you as soon as we do.",
          "",
          "Thank you for your patience and continued interest in [Company Name].",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
    ],
  },
  {
    stage: "3. Technical Test",
    stageColor: COLOR.blue,
    statuses: [
      {
        status: "Pending",
        badgeBg: "DBEAFE", badgeText: COLOR.blue,
        subject: "Technical assessment invitation – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Congratulations on progressing in our recruitment process for the [Job Title] role!",
          "",
          "As the next step, we'd like to invite you to complete a technical assessment. Details are as follows:",
          "",
          "  • Assessment Platform: [Platform Name / Link]",
          "  • Duration: [X hours]",
          "  • Deadline: [Date and Time]",
          "  • Topics Covered: [e.g., Data Structures, SQL, System Design]",
          "",
          "Please ensure you attempt the test in a stable, distraction-free environment. If you face any technical issues, contact us immediately at [support email].",
          "",
          "We look forward to seeing your work!",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "In Progress",
        badgeBg: "D1FAE5", badgeText: COLOR.teal,
        subject: "Technical test in progress – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We can see that you've started the technical assessment for the [Job Title] role — great!",
          "",
          "This is just a friendly reminder that the test must be completed by [Deadline Date & Time]. If you encounter any issues, please reach out to us at [support email] without delay.",
          "",
          "Wishing you all the best!",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Completed",
        badgeBg: "D1FAE5", badgeText: COLOR.teal,
        subject: "Technical test received – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for completing the technical assessment for the [Job Title] position. We have received your submission and our technical team will be evaluating it.",
          "",
          "We aim to share the outcome within [X business days]. We'll be in touch shortly.",
          "",
          "Thank you for your time and effort!",
          "",
          "Warm regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Cleared",
        badgeBg: "DCFCE7", badgeText: COLOR.green,
        subject: "Technical test cleared! – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We're thrilled to share that you have successfully cleared the technical assessment for the [Job Title] role. Well done!",
          "",
          "You will be contacted shortly to schedule the next stage — the Technical Interview. Please keep your calendar available for [suggested dates/window].",
          "",
          "Congratulations once again!",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Failed",
        badgeBg: "FEE2E2", badgeText: COLOR.red,
        subject: "Technical assessment outcome – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for completing the technical assessment for the [Job Title] position.",
          "",
          "After reviewing your submission, we regret to inform you that the results did not meet the qualifying threshold for this role. We recognise the effort you put in, and we genuinely appreciate your participation.",
          "",
          "We encourage you to continue honing your skills and to apply again in the future when another suitable opportunity arises.",
          "",
          "We wish you all the best.",
          "",
          "Kind regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Rejected",
        badgeBg: "FEE2E2", badgeText: COLOR.red,
        subject: "Update on your application – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for participating in the technical assessment for the [Job Title] role.",
          "",
          "After evaluating the results alongside the overall candidate pool, we've decided not to proceed with your application at this stage. Please know that this was a difficult decision given the strong field of candidates.",
          "",
          "We'll keep your profile on record and may reach out for future opportunities that align with your skills.",
          "",
          "Thank you for your time.",
          "",
          "Warm regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "On Hold",
        badgeBg: "FEF3C7", badgeText: COLOR.amber,
        subject: "Technical assessment on hold – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We'd like to inform you that the review of the technical assessment for the [Job Title] role is temporarily on hold due to [internal scheduling / panel availability].",
          "",
          "We expect to resume the process by [estimated date] and will update you as soon as we have a decision.",
          "",
          "Thank you for your patience.",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
    ],
  },
  {
    stage: "4. Technical Interview",
    stageColor: COLOR.blue,
    statuses: [
      {
        status: "Pending",
        badgeBg: "DBEAFE", badgeText: COLOR.blue,
        subject: "Technical interview invitation – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Congratulations on clearing the technical assessment! We are pleased to invite you for the Technical Interview for the [Job Title] role.",
          "",
          "Interview Details:",
          "  • Date: [Date]",
          "  • Time: [Time] ([Timezone])",
          "  • Format: [Video Call / In-Person]",
          "  • Platform/Location: [Zoom Link / Office Address]",
          "  • Interviewers: [Interviewer Name(s) & Designation(s)]",
          "  • Duration: Approximately [X] minutes",
          "",
          "The interview will cover [e.g., system design, coding, past projects]. Please come prepared with examples from your experience.",
          "",
          "Please confirm your availability by replying to this email. If you need to reschedule, let us know at least [X hours] in advance.",
          "",
          "Best of luck!",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "In Progress",
        badgeBg: "D1FAE5", badgeText: COLOR.teal,
        subject: "Reminder: Technical interview today – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "This is a friendly reminder that your Technical Interview for the [Job Title] role is scheduled for today.",
          "",
          "  • Time: [Time] ([Timezone])",
          "  • Platform/Location: [Link / Address]",
          "",
          "Please ensure your setup (audio, video, internet) is working properly if it is a virtual interview. We look forward to our conversation!",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Completed",
        badgeBg: "D1FAE5", badgeText: COLOR.teal,
        subject: "Thank you for your technical interview – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for attending the Technical Interview for the [Job Title] role at [Company Name]. It was a pleasure speaking with you.",
          "",
          "Our team will now evaluate the interview and you can expect to hear from us within [X business days] regarding the next steps.",
          "",
          "We appreciate your time and enthusiasm.",
          "",
          "Warm regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Cleared",
        badgeBg: "DCFCE7", badgeText: COLOR.green,
        subject: "Technical interview cleared! – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We are delighted to inform you that you have successfully cleared the Technical Interview for the [Job Title] role. The panel was impressed with your knowledge and approach — well done!",
          "",
          "You will be contacted soon to schedule the Managerial Interview. Please keep your schedule open for [date range].",
          "",
          "We're excited to continue this journey with you.",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Failed",
        badgeBg: "FEE2E2", badgeText: COLOR.red,
        subject: "Technical interview outcome – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for your time and effort during the Technical Interview for the [Job Title] position.",
          "",
          "After careful evaluation by our technical panel, we regret to share that we will not be moving forward with your candidacy at this stage. The decision was closely considered and we acknowledge the effort you demonstrated.",
          "",
          "We wish you continued success and encourage you to apply for future roles that match your expertise.",
          "",
          "Kind regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Rejected",
        badgeBg: "FEE2E2", badgeText: COLOR.red,
        subject: "Update on your application – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for your participation in the Technical Interview for the [Job Title] role.",
          "",
          "After thorough review by our panel, we have decided not to advance your application further. We appreciate the time you dedicated to this process.",
          "",
          "Your profile will remain in our talent pool for consideration for future roles.",
          "",
          "Thank you and all the best.",
          "",
          "Warm regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "On Hold",
        badgeBg: "FEF3C7", badgeText: COLOR.amber,
        subject: "Interview decision on hold – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for your time during the Technical Interview. We wanted to let you know that the decision on your candidacy is currently on hold as our team completes the evaluation process.",
          "",
          "We appreciate your patience and expect to share an update by [estimated date].",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
    ],
  },
  {
    stage: "5. Managerial Interview",
    stageColor: COLOR.blue,
    statuses: [
      {
        status: "Pending",
        badgeBg: "DBEAFE", badgeText: COLOR.blue,
        subject: "Managerial interview invitation – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Congratulations on clearing the Technical Interview! You've done exceptionally well, and we are excited to invite you for the Managerial Interview.",
          "",
          "Interview Details:",
          "  • Date: [Date]",
          "  • Time: [Time] ([Timezone])",
          "  • Format: [Video Call / In-Person]",
          "  • Interviewer: [Manager Name], [Designation]",
          "  • Duration: Approximately [X] minutes",
          "",
          "This round will focus on your leadership style, team collaboration, problem-solving approach, and cultural fit with [Company Name].",
          "",
          "Please confirm your availability at your earliest convenience.",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "In Progress",
        badgeBg: "D1FAE5", badgeText: COLOR.teal,
        subject: "Reminder: Managerial interview today – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Your Managerial Interview for the [Job Title] role is scheduled for today. Here's a quick reminder of the details:",
          "",
          "  • Time: [Time] ([Timezone])",
          "  • Platform/Location: [Link / Address]",
          "  • Interviewer: [Manager Name]",
          "",
          "We look forward to our conversation today!",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Completed",
        badgeBg: "D1FAE5", badgeText: COLOR.teal,
        subject: "Thank you for your managerial interview – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for meeting with [Manager Name] for the Managerial Interview. It was wonderful speaking with you and learning more about your leadership experiences.",
          "",
          "We will share the outcome of the interview within [X business days].",
          "",
          "Warm regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Cleared",
        badgeBg: "DCFCE7", badgeText: COLOR.green,
        subject: "Managerial interview cleared! – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We're very happy to let you know that you have successfully cleared the Managerial Interview. [Manager Name] was pleased with your insight and collaborative spirit.",
          "",
          "You are now being advanced to the HR Final Round. We'll contact you shortly to arrange the scheduling.",
          "",
          "Congratulations — you're almost there!",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Failed",
        badgeBg: "FEE2E2", badgeText: COLOR.red,
        subject: "Managerial interview outcome – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for attending the Managerial Interview for the [Job Title] position.",
          "",
          "After careful deliberation, we regret to inform you that we are unable to move your candidacy forward at this time. This was a very competitive round and the decision was not taken lightly.",
          "",
          "We value your time and wish you every success in your career.",
          "",
          "Kind regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Rejected",
        badgeBg: "FEE2E2", badgeText: COLOR.red,
        subject: "Update on your application – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for taking part in the Managerial Interview for the [Job Title] role.",
          "",
          "We have concluded our assessment and regret to share that we will not be proceeding with your application at this stage. We truly appreciate the time and effort you have invested in this process.",
          "",
          "We'll retain your profile and may reach out when a suitable opportunity arises.",
          "",
          "Thank you and best wishes.",
          "",
          "Warm regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "On Hold",
        badgeBg: "FEF3C7", badgeText: COLOR.amber,
        subject: "Interview decision on hold – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for attending the Managerial Interview. We'd like to inform you that the evaluation of this round is temporarily on hold while we align internally.",
          "",
          "We will provide an update by [estimated date]. Thank you for your continued patience.",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
    ],
  },
  {
    stage: "6. HR Final Round",
    stageColor: COLOR.blue,
    statuses: [
      {
        status: "Pending",
        badgeBg: "DBEAFE", badgeText: COLOR.blue,
        subject: "HR Final Round invitation – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Congratulations — you've reached the final stage of our recruitment process! We're excited to invite you for the HR Final Round for the [Job Title] position.",
          "",
          "Interview Details:",
          "  • Date: [Date]",
          "  • Time: [Time] ([Timezone])",
          "  • Format: [Video Call / In-Person]",
          "  • Interviewer: [HR Name], [Designation]",
          "  • Duration: Approximately [X] minutes",
          "",
          "This session will cover compensation expectations, joining formalities, and an opportunity for you to ask any questions you may have about the role or company.",
          "",
          "Please confirm your availability by replying to this email.",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "In Progress",
        badgeBg: "D1FAE5", badgeText: COLOR.teal,
        subject: "Reminder: HR Final Round today – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "This is a reminder that your HR Final Round for the [Job Title] role is happening today.",
          "",
          "  • Time: [Time] ([Timezone])",
          "  • Platform/Location: [Link / Address]",
          "",
          "Please have any questions ready — we'd love to address them all. See you soon!",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Completed",
        badgeBg: "D1FAE5", badgeText: COLOR.teal,
        subject: "HR Final Round completed – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for attending the HR Final Round for the [Job Title] role. It was great speaking with you and we're pleased with how the conversation went.",
          "",
          "Our team will now complete the final evaluation and we'll share an update with you within [X business days].",
          "",
          "Thank you for your patience.",
          "",
          "Warm regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Cleared",
        badgeBg: "DCFCE7", badgeText: COLOR.green,
        subject: "Exciting news – You've cleared the HR Final Round! | [Job Title]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We are thrilled to let you know that you have successfully cleared the HR Final Round for the [Job Title] role at [Company Name]!",
          "",
          "Our team will now prepare your offer details and you can expect to receive formal communication shortly. Please keep an eye on your inbox.",
          "",
          "We're truly looking forward to having you on board!",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Failed",
        badgeBg: "FEE2E2", badgeText: COLOR.red,
        subject: "HR Final Round outcome – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for your time and sincerity throughout the recruitment process, especially during the HR Final Round.",
          "",
          "We regret to inform you that after final deliberation, we are unable to extend an offer at this time. This decision was incredibly difficult given your performance through the process.",
          "",
          "We will be keeping your profile on record and hope to connect with you for future opportunities. We wish you the very best in your career.",
          "",
          "Kind regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Rejected",
        badgeBg: "FEE2E2", badgeText: COLOR.red,
        subject: "Update regarding your application – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you sincerely for your participation in the HR Final Round for the [Job Title] position.",
          "",
          "After careful consideration, we regret to share that we will not be moving forward with your candidacy. Please know that this decision was not a reflection of your potential, and we appreciate the time and effort you've invested.",
          "",
          "We'd like to stay connected and will reach out if a suitable opportunity comes up.",
          "",
          "Thank you and best wishes.",
          "",
          "Warm regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "On Hold",
        badgeBg: "FEF3C7", badgeText: COLOR.amber,
        subject: "Final round decision on hold – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for completing the HR Final Round. We'd like to inform you that the decision is currently on hold while certain internal approvals are in process.",
          "",
          "We expect to revert with an update by [estimated date] and sincerely appreciate your patience.",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
    ],
  },
  {
    stage: "7. Offer Preparation",
    stageColor: COLOR.blue,
    statuses: [
      {
        status: "Pending",
        badgeBg: "DBEAFE", badgeText: COLOR.blue,
        subject: "Offer in preparation – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We're pleased to share that you have successfully completed all rounds of our interview process for the [Job Title] role!",
          "",
          "Our team is currently preparing your offer letter, which will be shared with you within [X business days]. We appreciate your patience during this stage.",
          "",
          "If you have any questions in the meantime, please don't hesitate to reach out.",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "In Progress",
        badgeBg: "D1FAE5", badgeText: COLOR.teal,
        subject: "Your offer is being finalised – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We wanted to keep you updated — your offer letter is currently being finalised and will be sent to you very shortly.",
          "",
          "Thank you for your patience. We're excited to move forward with you!",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Completed",
        badgeBg: "D1FAE5", badgeText: COLOR.teal,
        subject: "Offer letter ready – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Your offer letter has been prepared and will be sent to you separately in a formal offer communication.",
          "",
          "Please review it carefully and let us know if you have any questions.",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "On Hold",
        badgeBg: "FEF3C7", badgeText: COLOR.amber,
        subject: "Offer preparation on hold – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We wanted to provide a quick update — the preparation of your offer is temporarily on hold due to [budgetary review / pending approvals].",
          "",
          "We fully intend to proceed and expect to share the offer by [estimated date]. We sincerely appreciate your continued patience.",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Rejected",
        badgeBg: "FEE2E2", badgeText: COLOR.red,
        subject: "Important update regarding your offer – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We sincerely regret to inform you that we are unable to proceed with making an offer for the [Job Title] role at this time due to [budget constraints / a change in business requirements / internal restructuring].",
          "",
          "This is in no way a reflection of your ability or performance during our process, and we are truly sorry for any inconvenience this may cause.",
          "",
          "We would like to stay in touch and will certainly reach out when a suitable opening arises.",
          "",
          "Thank you for your time and understanding.",
          "",
          "Kind regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
    ],
  },
  {
    stage: "8. Offer Issued",
    stageColor: COLOR.blue,
    statuses: [
      {
        status: "Pending",
        badgeBg: "DBEAFE", badgeText: COLOR.blue,
        subject: "Offer letter – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We are delighted to extend a formal offer of employment to you for the position of [Job Title] at [Company Name].",
          "",
          "Please find your offer letter attached to this email. Key highlights:",
          "  • Designation: [Job Title]",
          "  • Department: [Department]",
          "  • CTC: [Compensation Package]",
          "  • Date of Joining: [Proposed Date]",
          "  • Reporting To: [Manager Name]",
          "",
          "Please review the offer carefully and revert with your acceptance by [deadline date]. If you have any questions or would like to discuss any aspect of the offer, please feel free to reach out.",
          "",
          "We are very excited about the prospect of you joining our team!",
          "",
          "Warm regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Completed",
        badgeBg: "D1FAE5", badgeText: COLOR.teal,
        subject: "Offer letter confirmation – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "This is to confirm that your offer letter for the [Job Title] position has been sent to your registered email address. Please check your inbox (and spam/junk folder if needed).",
          "",
          "If you haven't received it, please reach out immediately and we'll resend it.",
          "",
          "We look forward to your response by [deadline date].",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Rejected",
        badgeBg: "FEE2E2", badgeText: COLOR.red,
        subject: "Offer withdrawal – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We regret to inform you that due to [unforeseen circumstances / a change in business priorities / budget freeze], we are required to withdraw the offer extended to you for the [Job Title] position.",
          "",
          "We understand this is disappointing news and sincerely apologise for the inconvenience this may cause you. We hold you in high regard and hope to reconnect in the future.",
          "",
          "Thank you for your understanding.",
          "",
          "Kind regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "On Hold",
        badgeBg: "FEF3C7", badgeText: COLOR.amber,
        subject: "Offer on hold – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We'd like to inform you that the offer previously extended to you for the [Job Title] role is temporarily on hold due to [internal approvals / business changes].",
          "",
          "We will provide an update by [estimated date]. We assure you that your candidacy is very much valued and we will reconnect as soon as possible.",
          "",
          "Thank you for your patience and understanding.",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
    ],
  },
  {
    stage: "9. Offer Accepted",
    stageColor: COLOR.blue,
    statuses: [
      {
        status: "Completed",
        badgeBg: "DCFCE7", badgeText: COLOR.green,
        subject: "Welcome to [Company Name]! | Offer accepted – [Job Title]",
        body: [
          "Dear [Candidate Name],",
          "",
          "We're absolutely thrilled that you've accepted the offer for the [Job Title] role at [Company Name]. Welcome to the team!",
          "",
          "Here are your next steps:",
          "  • Joining Date: [Date]",
          "  • Reporting Time: [Time]",
          "  • Reporting Location: [Office Address / Virtual Link]",
          "  • Documents to Bring: [List of documents]",
          "  • Point of Contact on Day 1: [HR Contact Name & Number]",
          "",
          "We will send you a detailed pre-joining kit with everything you need to know before your first day.",
          "",
          "We can't wait to have you with us. See you on [Joining Date]!",
          "",
          "Warm regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "Rejected",
        badgeBg: "FEE2E2", badgeText: COLOR.red,
        subject: "We're sorry to see you go – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for letting us know about your decision. While we're disappointed that you've declined the offer for the [Job Title] role, we completely respect your choice.",
          "",
          "If there is anything we could have done differently or if you'd like to share feedback on your experience, we'd genuinely appreciate hearing from you.",
          "",
          "We hope our paths cross again in the future. We wish you all the very best!",
          "",
          "Kind regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
      {
        status: "On Hold",
        badgeBg: "FEF3C7", badgeText: COLOR.amber,
        subject: "Offer acceptance on hold – [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for reaching out. We understand you need a little more time before making a final decision on the [Job Title] offer.",
          "",
          "We're happy to extend the acceptance deadline to [revised date]. Please do revert by then so we can move forward with joining formalities.",
          "",
          "We look forward to hearing from you.",
          "",
          "Best regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
    ],
  },
  {
    stage: "10. Joined",
    stageColor: COLOR.green,
    statuses: [
      {
        status: "Completed",
        badgeBg: "DCFCE7", badgeText: COLOR.green,
        subject: "Welcome aboard, [Candidate Name]! | Day 1 at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "It is our absolute pleasure to welcome you to the [Company Name] family! We're so glad to have you join us as our new [Job Title].",
          "",
          "Your onboarding schedule for today:",
          "  • [Time]: Welcome session with HR",
          "  • [Time]: IT setup and access provisioning",
          "  • [Time]: Team introduction with [Manager Name]",
          "  • [Time]: Office tour / Virtual orientation",
          "",
          "Your buddy / point of contact for the first week is [Buddy Name] ([Buddy Contact]).",
          "",
          "Please don't hesitate to reach out to HR or your manager for anything you need. We're here to make your transition as smooth as possible.",
          "",
          "Here's to an exciting journey ahead!",
          "",
          "Warm regards,",
          "[HR Name]",
          "HR Team | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
    ],
  },
  {
    stage: "11. Rejected (Final)",
    stageColor: COLOR.red,
    statuses: [
      {
        status: "Rejected",
        badgeBg: "FEE2E2", badgeText: COLOR.red,
        subject: "Your application for [Job Title] at [Company Name]",
        body: [
          "Dear [Candidate Name],",
          "",
          "Thank you for your time and the genuine effort you've put into the recruitment process for the [Job Title] role at [Company Name].",
          "",
          "After thorough consideration, we regret to inform you that we will not be moving forward with your application at this time. Please know that this was a very difficult decision and reflects the high calibre of candidates we had in our process.",
          "",
          "We have tremendous respect for the talent and dedication you demonstrated throughout our interactions. We'd love to stay connected and would encourage you to apply for future roles that align with your background.",
          "",
          "We wish you every success in your career.",
          "",
          "Kind regards,",
          "[Recruiter Name]",
          "[Recruiter Title] | [Company Name]",
          "[Email] | [Phone]",
        ],
      },
    ],
  },
];

// ───────────────────────── BUILD DOC ─────────────────────────

const children = [];

// Cover heading
children.push(
  new Paragraph({
    children: [new TextRun({ text: "Hiring Pipeline", font: "Arial", size: 56, bold: true, color: COLOR.blue })],
    alignment: AlignmentType.CENTER,
    spacing: { before: 400, after: 120 },
  }),
  new Paragraph({
    children: [new TextRun({ text: "Email Templates by Stage & Status", font: "Arial", size: 28, color: COLOR.gray })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 120 },
  }),
  new Paragraph({
    children: [new TextRun({ text: "[Company Name]  •  HR Department", font: "Arial", size: 22, color: "#9CA3AF", italics: true })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 400 },
  }),
  divider(COLOR.blue),
  new Paragraph({ children: [new TextRun({ text: "Usage Instructions", font: "Arial", size: 24, bold: true, color: COLOR.darkGray })], spacing: { before: 200, after: 120 } }),
  para("Replace all placeholders in [square brackets] with actual values before sending. Fields like [Candidate Name], [Job Title], [Company Name], [Recruiter Name], dates, and links must all be customised per candidate."),
  para("Each template is formatted with a clear Subject line and email Body. Templates are organised by stage and status for quick reference."),
  new Paragraph({ children: [new PageBreak()] }),
);

templates.forEach((stg, si) => {
  children.push(heading1(`Stage ${si + 1}: ${stg.stage.replace(/^\d+\. /, "")}`, stg.stageColor));
  children.push(divider());

  stg.statuses.forEach((st, idx) => {
    if (idx > 0) children.push(...space(1));

    children.push(statusBadge(`Status: ${st.status}`, st.badgeBg, st.badgeText));
    children.push(...space(1));
    children.push(emailBox(st.subject, st.body));
    children.push(...space(2));
  });

  if (si < templates.length - 1) {
    children.push(new Paragraph({ children: [new PageBreak()] }));
  }
});

const doc = new Document({
  styles: {
    default: { document: { run: { font: "Arial", size: 22 } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 36, bold: true, font: "Arial", color: COLOR.blue },
        paragraph: { spacing: { before: 400, after: 160 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 28, bold: true, font: "Arial", color: COLOR.darkGray },
        paragraph: { spacing: { before: 280, after: 120 }, outlineLevel: 1 } },
    ],
  },
  sections: [{
    properties: {
      page: {
        size: { width: 12240, height: 15840 },
        margin: { top: 1080, right: 1080, bottom: 1080, left: 1080 },
      },
    },
    children,
  }],
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync("/mnt/user-data/outputs/Hiring_Pipeline_Email_Templates.docx", buf);
  console.log("Done");
});